version: '3'
services:
  dind:
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
    privileged : true
    volumes:
      - var_lib_docker:/var/lib/docker

volumes:
  var_lib_docker:
